### GET All
GET http://localhost:8080/api/v1/users

### GET first one
GET http://localhost:8080/api/v1/users/1

### Create one
POST http://localhost:8080/api/v1/users
Content-Type: application/json

{
  "id": "5",
  "name": "Костянтин Чоботар",
  "username": "Harsteel",
  "email": "chobotar@gmail.com",
  "phoneNumber": "0985459876",
  "gender": "Вішалка для дівчат"
}

#### Update one
PUT http://localhost:8080/api/v1/users/5
Content-Type: application/json

{
  "name": "Костянтин Чоботар",
  "username": "Harsteel",
  "email": "kostiantyn@gmail.com",
  "phoneNumber": "0951239876",
  "gender": "Вішалка для дівчат"
}

#### DELETE one
DELETE http://localhost:8080/api/v1/users/5